#https://school.programmers.co.kr/learn/courses/30/lessons/131124

SELECT MEMBER_NAME, REVIEW_TEXT, DATE_FORMAT(REVIEW_DATE,"%Y-%m-%d") AS REVIEW_DATE
FROM(SELECT MEMBER_NAME, COUNT(MEMBER_NAME) AS NUM , PRO.MEMBER_ID FROM REST_REVIEW as REVIEW
     INNER JOIN MEMBER_PROFILE as PRO ON PRO.MEMBER_ID = REVIEW.MEMBER_ID
     GROUP BY PRO.MEMBER_ID) A
JOIN (SELECT MAX(NUM) AS NUMBER
FROM (SELECT MEMBER_NAME, COUNT(MEMBER_NAME) AS NUM FROM REST_REVIEW as REVIEW
     INNER JOIN MEMBER_PROFILE as PRO ON PRO.MEMBER_ID = REVIEW.MEMBER_ID
     GROUP BY PRO.MEMBER_ID
     ) C
     ) B
ON A.NUM = B.NUMBER
JOIN REST_REVIEW ON A.MEMBER_ID = REST_REVIEW.MEMBER_ID
ORDER BY REVIEW_DATE, REVIEW_TEXT