#https://school.programmers.co.kr/learn/courses/30/lessons/131537

SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d") as SALES_DATE,PRODUCT_ID,USER_ID,SALES_AMOUNT FROM ONLINE_SALE
WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
UNION ALL
SELECT DATE_FORMAT(SALES_DATE,"%Y-%m-%d")as SALES_DATE,PRODUCT_ID,NULL as USER_ID,SALES_AMOUNT FROM OFFLINE_SALE
WHERE SALES_DATE >= '2022-03-01' AND SALES_DATE < '2022-04-01'
ORDER BY SALES_DATE, PRODUCT_ID,USER_ID