#https://school.programmers.co.kr/learn/courses/30/lessons/151141

SELECT HISTORY_ID, ROUND(DAILY_FEE*DURATION*(100- (CASE WHEN DISCOUNT_RATE IS NULL THEN 0 ELSE DISCOUNT_RATE END))/100,0) as FEE 
FROM (SELECT HISTORY_ID, DAILY_FEE, DATEDIFF(END_DATE,START_DATE)+1 as DURATION, DISCOUNT_RATE FROM CAR_RENTAL_COMPANY_RENTAL_HISTORY AS HISTORY
     INNER JOIN CAR_RENTAL_COMPANY_CAR AS CAR ON CAR.CAR_ID = HISTORY.CAR_ID
     LEFT JOIN CAR_RENTAL_COMPANY_DISCOUNT_PLAN as PLAN 
     ON (PLAN.CAR_TYPE = CAR.CAR_TYPE) AND ((DATEDIFF(END_DATE,START_DATE)+1 >= 90 AND PLAN.DURATION_TYPE = '90일 이상') OR
         (DATEDIFF(END_DATE,START_DATE)+1 >= 30 AND DATEDIFF(END_DATE,START_DATE)+1 < 90 AND PLAN.DURATION_TYPE = '30일 이상') OR
         (DATEDIFF(END_DATE,START_DATE)+1 >= 7 AND DATEDIFF(END_DATE,START_DATE)+1 < 30 AND PLAN.DURATION_TYPE = '7일 이상'))
     WHERE CAR.CAR_TYPE = '트럭'
     ) A
ORDER BY FEE DESC,HISTORY_ID DESC